### ISSUE TITLE
Change default branch to Master

### ISSUE THREAD

**Issue by TheoBr** [Likeminded/Likeminded#6]
The only branch in the original repo was tenex-development ( @hut8's development branch )

It is best practice to have a production branch named 'master', and have that be the 'default', front-facing branch. I have made the master branch already, if @mdjohns1 could quickly make it the default branch that'd be great

https://help.github.com/articles/setting-the-default-branch/

**Comment by TheoBr** [comment]
Ping on this, currently blocking other tasks

**Comment by mdjohns1** [comment]
The changes Tenex made may create the Staging site not the current production site.  Is there a way to roll it back once this is done to replicate the current production site?
